# Generated by Django 5.0.3 on 2024-04-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category_alter_product_description_and_more'),
        ('wishlist', '0002_wishlist_item_wishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishes', through='wishlist.Wishlist_Item', to='product.product'),
        ),
        migrations.AlterField(
            model_name='wishlist_item',
            name='wish_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_items', to='wishlist.wishlist'),
        ),
    ]
