# Generated by Django 4.2 on 2024-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_profile_email_profile_phone_alter_profile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
