# Generated by Django 4.2 on 2024-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_profile_email_alter_profile_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="full_name",
            new_name="full_name_profile",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
        migrations.AddField(
            model_name="profile",
            name="emailprofile",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phoneprofile",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
