# Generated by Django 5.0.3 on 2024-04-14 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_delivered_date_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 12, 28, 58, 660559, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
