# Generated by Django 5.0.3 on 2024-04-14 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 12, 49, 49, 141524, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
