# Generated by Django 4.2.7 on 2024-04-16 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 23, 2, 17, 302263, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
