# Generated by Django 4.2.7 on 2024-04-16 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 23, 3, 13, 453777, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
